version: '3.1'

services:
  web:
    image: nginx:alpine
    ports:
      - "8088:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
  app:
    build: .
    image: "login-app"
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=my_custom_secret_key
